notifications:
  email: false

os:
  - linux
#  - osx

language: cpp

compiler:
  - clang
  - gcc

install:
  - if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="g++-7" CC="gcc-7"; fi
  - if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - gcc-7
      - g++-7
      - clang-5.0

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTING=YES
  - make
  - ./gomoku test
  - ./gomoku_test
